# .github/workflows/deploy.yml
name: Deploy AI Stack Simple

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod

jobs:
  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    environment:
      name: development
      url: http://147.93.185.141:3000
    
    steps:
    - name: Deploy to Development Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 147.93.185.141
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /opt/ai-stack
          git pull origin main
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh
          ./scripts/health-check.sh

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod'
    environment:
      name: production
      url: http://147.93.181.151:3000
    
    steps:
    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 147.93.181.151
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /opt/ai-stack
          git pull origin main
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh
          ./scripts/health-check.sh

  notify:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [deploy-dev, deploy-prod]
    if: always()
    steps:
    - name: Deployment Complete
      run: |
        echo "Deployment Status:"
        echo "Development: ${{ needs.deploy-dev.result }}"
        echo "Production: ${{ needs.deploy-prod.result }}"